### ISSUE TITLE
support Lock Brightness and Contrast 

### ISSUE THREAD

**Issue by aiyou9** [vietanhdev/anylabeling#102]
some time the Brightness and Contrast of images from same equipment are similar

**Comment by ryouchinsa** [comment]
Thanks for your great tool AnyLabeling.

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, you can apply the same brightness/contrast values when you change the image.

![contrast](https://github.com/vietanhdev/anylabeling/assets/1954306/9fb88eda-8ea6-49b7-9a88-43c1f2d8ace3)
