### ISSUE TITLE
Qt xcb error?

### ISSUE THREAD

**Issue by GalSang17** [vietanhdev/anylabeling#108]
(py38) yangyang@ysd:~$ anylabeling 
QObject::moveToThread: Current thread (0x55efb47d7980) is not the object's thread (0x55efb56c97e0).
Cannot move to target thread (0x55efb47d7980)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/yangyang/miniconda3/envs/py38/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

my envs:
python=3.8
PyQt=5.15.7

**Comment by vietanhdev** [comment]
@GalSang17 You can try the following commands:
```
pip uninstall opencv-python
pip uninstall opencv-contrib-python
pip install opencv-python-headless
```
Source: <https://github.com/NVlabs/instant-ngp/discussions/300>.

**Comment by GalSang17** [comment]
> @GalSang17 You can try the following commands:
> 
> ```
> pip uninstall opencv-python
> pip uninstall opencv-contrib-python
> pip install opencv-python-headless
> ```
> 
> Source: [NVlabs/instant-ngp#300](https://github.com/NVlabs/instant-ngp/discussions/300).

yeah! it worked, thank you.

**Comment by vietanhdev** [comment]
@GalSang17  OpenCV has 4 packages for python: opencv-python, opencv-contrib-python, opencv-python-headless and opencv-contrib-python-headless.
The first two versions may cause some issues on some machines, mostly when used with PyQt.

**Comment by vietanhdev** [comment]
Install the `headless` version to use cv2:
```
pip install opencv-python-headless
```
Or
```
opencv-contrib-python-headless
```

**Comment by vongocminh778** [comment]
sudo apt install libxcb-xinerama0  to fixed problem worked for me.

**Comment by prob1995** [comment]
> `sudo apt install libxcb-xinerama0` to fixed problem worked for me.

this works for me! thanks!
