### ISSUE TITLE
Combine anylabeling with Grounded-SAM

### ISSUE THREAD

**Issue by hafidh561** [vietanhdev/anylabeling#11]
Hi @vietanhdev

I love your project and I want to support your project with some suggestions.
I have a suggestion for you, maybe you can combine anylabeling with repository [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) because Grounded-SAM project has zero shot object detection and makes anylabeling more better.

**Comment by vietanhdev** [comment]
Thank you for your suggestion.
