### ISSUE TITLE
/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by zk565** [vietanhdev/anylabeling#110]
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/zk/conda/envs/anylabeling/lib/python3.8/site-packages/matplotlib/_path.cpython-38-x86_64-linux-gnu.so)

**Comment by vietanhdev** [comment]
Hi @zk565,
Please try those commands:

```
conda install -c conda-forge gcc
conda install -c conda-forge gxx
```

References: <https://stackoverflow.com/questions/77150540/importerror-lib-x86-64-linux-gnu-libstdc-so-6-version-glibcxx-3-4-29-not>.
