### ISSUE TITLE
Suggestion - Integrate MobileSAM into the pipeline for lightweight and faster inference

### ISSUE THREAD

**Issue by mdimtiazh** [vietanhdev/anylabeling#117]
Reference: https://github.com/ChaoningZhang/MobileSAM

 

Our project performs on par with the original SAM and keeps exactly the same pipeline as the original SAM except for a change on the image encode, therefore, it is easy to Integrate into any project.

 

MobileSAM is around 60 times smaller and around 50 times faster than original SAM, and it is around 7 times smaller and around 5 times faster than the concurrent FastSAM. The comparison of the whole pipeline is summarzed as follows:

 

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/102718175/ecc801de-a7c9-4ccb-84f7-477e359a1892)

 

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/102718175/39f257e2-dca0-4956-bdb1-4326e6b5d13b)

 

 

 

Best Wishes,

 

Qiao

**Comment by vietanhdev** [comment]
Hi @mdimtiazh !
Thank you for your suggestion. However, it's best to have ONNX format models to avoid installing PyTorch, which is ~700MB to 1GB+ with this package. 
We may need to wait for the ONNX conversion from the MobileSAM's authors.

**Comment by vietanhdev** [comment]
@mdimtiazh Finished integration in v0.3.0.
