### ISSUE TITLE
bad segmentation 

### ISSUE THREAD

**Issue by nisanaryal-MTEG** [vietanhdev/anylabeling#119]
I just updated to 0.3.2 and there seems to be some issue. The segmentation mask is wrong for mobileSAM as well as Vit-b version.(gives almost all the images as output). I think this is due to some error during the latest update. Please review it.

**Comment by nisanaryal-MTEG** [comment]
Previously, I had made a user version of SAM and it was working fine. I tried with that one and the following error occurred. I hope it will be helpful to find the bug. 
![image](https://github.com/vietanhdev/anylabeling/assets/91938771/2986c023-b909-4d38-ad1d-5b4b593b073a)

**Comment by nisanaryal-MTEG** [comment]
from pip, 0.2.24 is working fine, something went wrong in 0.3.0. 

Hope this will be helpful.

**Comment by vietanhdev** [comment]
@nisanaryal-MTEG Thank you for testing out.
The models need to be exported by samexporter https://github.com/vietanhdev/samexporter. Previous models may not be compatible.
Have you downloaded new models using the UI?

**Comment by nisanaryal-MTEG** [comment]
@vietanhdev I just selected the model from the option, the models are auto downloaded aren't they?. If not then the problem might be because of local downloaded file with the same name from previous version. 

I created the onnx with my own code and matched the input and output after watching the documentation. I did not know that there was a separate repository for onnx, thanks for the hard work.

**Comment by nisanaryal-MTEG** [comment]
![image](https://github.com/vietanhdev/anylabeling/assets/91938771/4cf1d61a-86c6-4618-8d94-cb9c89e340f8)
I selected a model that I normally dont use and tested it, the error still exits.

![image](https://github.com/vietanhdev/anylabeling/assets/91938771/83473943-fd7a-44dd-8f93-534897ba9ab6)
The output comes as the whole image.

I am using windows and install/upgraded using PIP. 

I think there is some problem.

**Comment by vietanhdev** [comment]
@nisanaryal-MTEG There is an issue here: Labeling UI is not blocked while downloading the model. Please wait until the message "Downloading http..." disappears.
I will fix this issue in the next version.

**Comment by vietanhdev** [comment]
For the MobileSAM, please note that it has been only trained on 1% of the SAM dataset. Maybe the generalization is not as good as the original models, causing bad results on special objects or domains (just my guess).

**Comment by nisanaryal-MTEG** [comment]
@vietanhdev sorry for the confusion, the model downloaded properly last time, I just took the image to convey that I am using the latest version of model. 

I converted MobileSAM to onnx with my code and tested on 0.2.24, it is working fine. All the models are giving wrong output from 0.3.0. The surgical image from previous comment was from vit-l.

I have not tried on another PC yet so this might be a local problem as well. I will get back to you after testing on another pc.

**Comment by vietanhdev** [comment]
Could you try following:
- Delete `$HOME/anylabeling_data` and then reopen the program. The models will be downloaded from scratch.
- Send me some images and results (0.2.24, 0.3.2) if possible. My email: vietanh.dev@gmail.com.
Thank you!

**Comment by ydzhang12345** [comment]
same here. Results are really bad for v0.3.2. Using v0.2.24 is fine

**Comment by vietanhdev** [comment]
@nisanaryal-MTEG @ydzhang12345 
Could you help me to test v0.3.3? <https://github.com/vietanhdev/anylabeling/releases/tag/v0.3.3>.
I fixed an issue when casting the mask value, but I don't know if it can fix your issue.
I still cannot reproduce the issue on my machine, so it's best if you can provide more details:
- Your OS
- Your images
- Steps to get the wrong results. How is it different from the last version (0.2.x)
Thank you very much!

**Comment by nisanaryal-MTEG** [comment]
@vietanhdev the problem is solved in the v0.3.3. Thanks for the hard work
