### ISSUE TITLE
integrating FastSam

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [vietanhdev/anylabeling#120]
Hi
Thanks for your work on this great repo. 

I was wondering if you are planning to implement fastsam in the future? if yes, when?
Here is the original repo: https://github.com/CASIA-IVA-Lab/FastSAM

Thanks in advance!

**Comment by vietanhdev** [comment]
@SuroshAhmadZobair Yes. It's in the plan. However, it takes some time to convert that model into ONNX first.
Currently, I need to fix a bug on SAM inference 0.3.x.
Could you please help with this integration?
