### ISSUE TITLE
anylabeling cannot work in auto segmention with version 0.3.2

### ISSUE THREAD

**Issue by futureflsl** [vietanhdev/anylabeling#122]
I try version 0.3.2,find that bad segmention,like this,I try MobileSam and Vit-b ,it work bad
![360截图20230701221702828](https://github.com/vietanhdev/anylabeling/assets/23259315/c3e00c58-baf3-4b94-b0a0-ad18ff3b4d79)

**Comment by vietanhdev** [comment]
@futureflsl Could you send me that image for debugging? 
My email: <vietanh.dev@gmail.com>.

**Comment by vietanhdev** [comment]
@futureflsl Please check v0.3.3 to see if it fixed your issue. <https://github.com/vietanhdev/anylabeling/releases/tag/v0.3.3>.

If it's not, I need some more information for debugging:
- Your OS
- Your images
- Steps to get the wrong results. How is it different from the last version (0.2.x)

Thank you very much!

**Comment by vietanhdev** [comment]
Close as the issue has been fixed in v0.3.3.
