### ISSUE TITLE
Using output JSON to train a custom detection model

### ISSUE THREAD

**Issue by servetcoskun** [vietanhdev/anylabeling#128]
This is not directly anylabel related, but it would be great if someone could help point in the right direction for using the output JSON file after segmenting many objects in multiple pictures to e.g., train a custom yolo model. Are there any easy to use guides on how to do this?

Thanks!

**Comment by aiyou9** [comment]
> 
use this fork project util tool to converter to yolo or coco format file
https://github.com/CVHub520/X-AnyLabeling/blob/main/tools/label_converter.py

**Comment by servetcoskun** [comment]
Thanks, will try this. Closing this as its not _directly_ related to anylabel.
