### ISSUE TITLE
What happened with COCO annotations?

### ISSUE THREAD

**Issue by hdnh2006** [vietanhdev/anylabeling#133]
I started to use again this repo.

I remember at the beginning the outputs provided where in COCO format, am I wrong? 🤔🤔

Can you let me know how to read COCO annotations? I don't want to label in labelme format because I already have my annotations in COCO format. I loved that feature from this repo 😢😢

I don't know if I am wrong, please explain. Thank you.

**Comment by ryouchinsa** [comment]
Thanks for your great tool AnyLabeling.

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, you can label polygons using Segment Anything models and import/export the COCO format.

![sam_polygon](https://github.com/ryouchinsa/sam-cpp-macos/assets/1954306/4640e139-c533-4b8c-b27b-e02a401b9bbd)

**Comment by hdnh2006** [comment]
> @hdnh2006 This tool didn't use COCO format from the beginning. You can try this tool to convert the data: https://github.com/fcakyon/labelme2coco. I will add the support to convert between formats in this repo.

So, I was confused. Thanks.
