### ISSUE TITLE
Error saving label data

### ISSUE THREAD

**Issue by Hung-3008** [vietanhdev/anylabeling#142]
Hello, recently I imported some of my annotation files and edited them with anylabeling. However, I cannot save the file. I am using the latest release version on windows.

**Comment by asifahmed1997bd** [comment]
I am facing the same problem. The  The following error show , evetime i save the file.

>  File "C:\Users\lenovo\miniconda3\envs\anylabeling\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'E:'

**Comment by asifahmed1997bd** [comment]
> Hello, recently I imported some of my annotation files and edited them with anylabeling. However, I cannot save the file. I am using the latest release version on windows.

I am facing the same problem. The The following error show , evetime i save the file.

> File "C:\Users\lenovo\miniconda3\envs\anylabeling\lib\ntpath.py", line 703, in relpath
raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'E:

**Comment by vietanhdev** [comment]
@asifahmed1997 Could you provide the full error log here?

**Comment by asifahmed1997bd** [comment]
> @ASIFAHMED1997 Could you provide the full error log here?

Thank you for your kind reply. i have solved it just a minute ago. The problem was, that any labeling was taking the absolute path, and I have changed the directory path. Now it's working.haha. Thanks for making it public. It's a great tool.
