### ISSUE TITLE
can't work  on mac os  arm M1

### ISSUE THREAD

**Issue by RFSN** [vietanhdev/anylabeling#149]
some logs :
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               anylabeling [73015]
Path:                  /Applications/AnyLabeling.app/Contents/MacOS/anylabeling
Identifier:            AnyLabeling
Version:               0.0.0 (???)
Code Type:             X86-64 (Translated)
Parent Process:        anylabeling [73013]
Responsible:           anylabeling [73013]
User ID:               502

Date/Time:             2023-09-30 20:59:51.7722 +0800
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        09850DFA-9E1A-0A5C-56AE-4AD7DE9EB216

Sleep/Wake UUID:       8936FD43-8962-4C34-96DA-FE8F6E704EF2

Time Awake Since Boot: 120000 seconds
Time Since Wake:       35874 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x7FF8AB51AA78)

Crashed Thread:        3  QThread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   anylabeling [73015]

Application Specific Information:
abort() called

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x7FF8AB51AA78)

Thread 0::  Dispatch queue: com.apple.main-thread
0   libQt5Gui.5.dylib             	       0x12285f2d4 0x12262b000 + 2310868
1   libQt5Gui.5.dylib             	       0x122774007 0x12262b000 + 1347591

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7fff952b4 0x7ff7fff91000 + 17076

Thread 2:: com.apple.NSEventThread
0   ???                           	    0x7ff8ab51aa78 ???

thanks !

**Comment by vietanhdev** [comment]
I also use Mac M1.
Which release did you use? Have you tried [AnyLabeling.dmg](https://github.com/vietanhdev/anylabeling/releases/download/v0.3.3/AnyLabeling.dmg)?

**Comment by RFSN** [comment]
yes  
use  [AnyLabeling.dmg](https://github.com/vietanhdev/anylabeling/releases/download/v0.3.3/AnyLabeling.dmg)  v0.33 .
it‘s not work , and  wait lanuch app maybe use 1-3 minute , so slow .
when   download this model(ClashX Pro  、Surge  ) .  it's crash。

**Comment by vietanhdev** [comment]
I will look into .dmg version.
In the meantime, you can use the Python version instead.

**Comment by RFSN** [comment]
thanks
system info:
  型号名称：	MacBook Pro
  型号标识符：	MacBookPro18,2
  芯片：	Apple M1 Max
  核总数：	10（8性能和2能效）
  内存：	32 GB
  系统固件版本：	10151.1.1
  操作系统加载程序版本：	10151.1.1
 OS code : 14.0 (23A344)
thank you

**Comment by RFSN** [comment]
Python version  
 anylabeling&  start up so fastly .
 anylabeling    start up so  slow .
 it's maybe  help  to  dmg package .

**Comment by vietanhdev** [comment]
Thank you for your feedback!
The issue will be solved in the next version.
