### ISSUE TITLE
label polygon with holes

### ISSUE THREAD

**Issue by 22strongestme** [vietanhdev/anylabeling#154]
how to label an object using polygon with holes
![image](https://github.com/vietanhdev/anylabeling/assets/55016895/3fcd111c-5d79-4345-bedd-74e3aa0f79bf)
i want to label the banana_chips, and cut out the nut in the pic

**Comment by vietanhdev** [comment]
Hi @22strongestme ,
We don't have any plan to support this feature soon.
Thank you very much for your interest!

I will close this issue as it will not be update soon.
