### ISSUE TITLE
the problem about load SAM autolabeling

### ISSUE THREAD

**Issue by fatejzz** [vietanhdev/anylabeling#158]
while I load the offical model like SAM(download from https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.4.0) in custom model way,the program will shut down,and the console says"[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: x Got: 3 Expected: 4 Please fix either the inputs or the model."

**Comment by fscbird** [comment]
I also has this probles...

**Comment by vietanhdev** [comment]
Please use the [samexporter](https://github.com/vietanhdev/samexporter) to export ONNX models for the latest version of AnyLabeling.
Thank you!
