### ISSUE TITLE
Confusing WhatsThis mode on initial load

### ISSUE THREAD

**Issue by scottix** [vietanhdev/anylabeling#167]
I was trying to track down why the Toolbar buttons wouldn't work on initial load until after the second click.
Finally found the culprit.
https://github.com/vietanhdev/anylabeling/blob/e7fb9cae3f234243a17014f6dbd4b7391534da82/anylabeling/views/labeling/label_widget.py#L1069-L1071

Problem is it's a bit confusing to be in this mode on initial load as it's not the default behavior for applications.

I would suggest it's better to turn it off for now or create a button to invoke it.

**Comment by vietanhdev** [comment]
This will be fixed in the next version. Thank you!
