### ISSUE TITLE
pip install anylabeling failing with build wheel error in 3.12

### ISSUE THREAD

**Issue by epicman25** [vietanhdev/anylabeling#174]
I tried to install anylebeling with python 3.12.Previously when I had 3.10 it worked properly .But now its failing by giving the error ` AssertionError: Could not find cmake executable!`

![2024-05-03_12-15-31](https://github.com/vietanhdev/anylabeling/assets/67092102/43cea094-4826-4cdc-975d-04eb258454b5)

**Comment by epicman25** [comment]
I have locally tested by changing few of the versions on onnx and onnx-runtime.I will raise the PR.

**Comment by sunyongke** [comment]
I also meet this  error

Mac osx m3 pro + python3.12+ anylabeling-gpu

**Comment by vietanhdev** [comment]
Hi All,
Please try Python 3.8 with the CPU version.
ONNX and ONNXRuntime will be updated in the next version.
Thank you.
