### ISSUE TITLE
GroundingDINO

### ISSUE THREAD

**Issue by renzhenxuexi0** [vietanhdev/anylabeling#34]
Whether you can add GroundingDINO？
This model can annotate images using natural language.

**Comment by antopost** [comment]
You can already use [autodistill](https://github.com/autodistill/autodistill) for this.
But in my experience it's not yet far enough in development to be useful.

**Comment by vietanhdev** [comment]
Hi!
I closed this issue as this feature will not be added soon.
Thank you for your interest.
