### ISSUE TITLE
Support OCR task

### ISSUE THREAD

**Issue by v-vietlq4** [vietanhdev/anylabeling#41]
Have you got a plan to integrate annotation for the OCR task?
It's the same as https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel

**Comment by vietanhdev** [comment]
@v-vietlq4  The text labeling is already supported following features:
- Add text for the image
- Add text for objects
- Add group/ungroup objects (for KIE)

![image](https://user-images.githubusercontent.com/18329471/233149737-67e78364-472f-4904-89d7-74d50e88a478.png)

![image](https://user-images.githubusercontent.com/18329471/233149906-4e935355-d378-418b-a20c-a417cc5fc66e.png)

However, the documentation needs to be added. And other advanced labeling features (for example complicated relationship or table annotation) can be added also. 

If you are interested and want to contribute to these features, please send me a message via my Facebook or my email vietanhdev [atttt] gmail dot com. Thank you!

**Comment by v-vietlq4** [comment]
Thanks anh Viet Anh!
I hope we'll collaborate in the future!
