### ISSUE TITLE
GRAY image errr

### ISSUE THREAD

**Issue by GitHubChrischen** [vietanhdev/anylabeling#42]
when load gray, image , app will error

**Comment by vietanhdev** [comment]
Hello,
Can you upload a sample of image causing error here?

**Comment by qqqhhh-any** [comment]
hey!You can fix this bug by modifying the function anylabeling/views/labeling/utils/opencv.py qt_img_to_cv_img,just like the code below:
def qt_img_to_cv_img(in_image):
    """
    allow to load rgb,gray image to inference
    """
    cv_image = qimage2ndarray.raw_view(in_image)
    # to uint8
    if cv_image.dtype != np.uint8:
        cv2.normalize(cv_image, cv_image, 0, 255, cv2.NORM_MINMAX)
        cv_image = np.array(cv_image, dtype=np.uint8)
    # to rgb
    if len(cv_image.shape) == 2 or cv_image.shape[2] == 1:
        cv_image = cv2.merge([cv_image, cv_image, cv_image])
    return cv_image

**Comment by vietanhdev** [comment]
Resolved in #47
