### ISSUE TITLE
ValueError: For rgb_view, the image must have 32 bit pixel size (use RGB32, ARGB32, or ARGB32_Premultiplied)

### ISSUE THREAD

**Issue by WangRongsheng** [vietanhdev/anylabeling#50]
When I import some grayscale mammogram images, it reports an error: ValueError: For rgb_view, the image must have 32 bit pixel size (use RGB32, ARGB32, or ARGB32_Premultiplied)

**Comment by vietanhdev** [comment]
Can you send me some images for reproducing?

**Comment by WangRongsheng** [comment]
![013](https://user-images.githubusercontent.com/55651568/233851932-a6d0dda9-c16e-43c5-b756-e27c9de5ab23.png)

![063](https://user-images.githubusercontent.com/55651568/233851942-8c0c0ab0-9b90-4402-a32d-67f7e298cd6c.png)

This is demo images, thank you!

**Comment by vietanhdev** [comment]
@WangRongsheng I have fixed it in master and Release v0.2.11.

**Comment by WangRongsheng** [comment]
thank you @vietanhdev
