### ISSUE TITLE
How SAM generates segmentation annotations from points?

### ISSUE THREAD

**Issue by WangRongsheng** [vietanhdev/anylabeling#53]
Hi Viet Anh,

I would like to ask you some questions. When I use SAM to do segmentation annotation, I use the **point** pattern. How does SAM determine the split area based on the points I enter?

Looking forward to your answer!

**Comment by vietanhdev** [comment]
The SAM is a deep learning model. The decoder receives 2 inputs:
- The embedding, which is the output of the encoder.
- The prompts (points: coordinates x, y of **point**, the box (coordinates x, y of box), and a mask).
It (the decoder) will run as a deep-learning image segmentation model to produce binary masks). After that, I use contour finding algorithm in OpenCV with the output (the first binary mask) to obtain the object boundaries.

**Comment by WangRongsheng** [comment]
Can you give some usage demo code? Thank you @vietanhdev
