### ISSUE TITLE
When using GPU 3070, there may be insufficient video memory.

### ISSUE THREAD

**Issue by GitHubChrischen** [vietanhdev/anylabeling#54]
Please do not infer all images in the folder at once. set or automatically pre-infer a few images according to the current video card model to ensure that the increase of video memory is within an acceptable range.

**Comment by vietanhdev** [comment]
Currently, the model only runs on 1 image once.
Can you capture the error messages?

**Comment by vietanhdev** [comment]
Documentation for GPU support: https://anylabeling.com/docs/gpu.
