### ISSUE TITLE
How  to use SAM with GPU?

### ISSUE THREAD

**Issue by yunfei920406** [vietanhdev/anylabeling#57]
I found when segment with SAM in anylabeling, the GPU is not used. How to address this issue?

**Comment by kime541200** [comment]
I have same question.

**Comment by myd510** [comment]
@yunfei920406 @kime541200 Because onnxruntime takes precedence over onnxruntime-gpu, all you need to do is remove onnxruntime from requirements-dev.txt, execute `pip install -r requirements-dev.txt` and  run the program or build it.

**Comment by myd510** [comment]
@yunfei920406 @kime541200 because onnxruntime takes precedence over onnxruntime-gpu, all you need to do is remove onnxruntime from requirements-dev.txt, execute `pip install -r requirements-dev.txt` and  run the program or build it.

**Comment by myd510** [comment]
@yunfei920406 @kime541200 Sorry, I forgot one thing, you have to make sure you have CUDA environment on your system.

**Comment by kime541200** [comment]
> @yunfei920406 @kime541200 Sorry, I forgot one thing, you have to make sure you have CUDA environment on your system.

Thank you so much for your help! It helped me a lot, and it was a great project!
