### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by ZJZ0405** [vietanhdev/anylabeling#62]
I get the following error when running in cpu environment.
"[ WARN:0@14.885] global net_impl.cpp:174 setUpNet DNN module was not built with CUDA backend; switching to CPU"

**Comment by vietanhdev** [comment]
It is only a warning - does not cause any problem with your program.

**Comment by ZJZ0405** [comment]
> It is only a warning - does not cause any problem with your program.

I was able to open the program normally, but when I used autotagging, the program crashed.I use ubuntu-desktop-20.04 and it tells me "Segmentation fault".I don't know why this happened.

**Comment by frankool** [comment]
but with this GPU is running?

**Comment by ZJZ0405** [comment]
> but with this GPU is running?

I read the source code and found that there are judgments about GPU and CPU. If I don't use GPU-accelerated DNN, I can open the software's GUI normally, but when I use the "Auto Labeling" function, the software will crash during loading. Because of this troublesome error message "segmentation fault", I cannot solve this problem without reading the source code completely. However, the problem may also be caused by not using "conda" to build the environment.

**Comment by vietanhdev** [comment]
@ZJZ0405 Please try with the newest code from master or v0.2.14 to see if the "Segmentation fault" is still there.

**Comment by ZJZ0405** [comment]
I still have the above problem. [Does your program support the function of inputting images with different sizes from those preset in ”yaml“?

**Comment by ZJZ0405** [comment]
@vietanhdev I found that I couldn’t add a custom model by changing the yaml after I upgraded to the new version. I plan to give up using it on the native system and switch to using it in the conda environment.
