### ISSUE TITLE
where is the onnx file path?

### ISSUE THREAD

**Issue by chunniunai220ml** [vietanhdev/anylabeling#72]
hi, thank for ur sharing, when i choose auto seg, the exe reminding loading samXXX.onnx file, but it's can not download successfully, so i try to download the pretrained SAM onnx file by hand, but i do not know where to place the file for AnyLabeling.exe

**Comment by xueyeyu** [comment]
windows 系统 
可能是 在个人文件夹  Users\用户名\anylabeling_data\models\   下面 
ONNX 地址   https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.2.0  
文档 https://anylabeling.com/docs 

may be in  c:\Users\XXX\anylabeling_data\models\

**Comment by vietanhdev** [comment]
@chunniunai220ml From AnyLabeling v0.2.22:
- Download models from [here](https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.4.0), extract.
- Load the models with **Custom Models** feature: https://anylabeling.com/docs/custom-models.
