### ISSUE TITLE
Shortcuts to reduce the labeling time.

### ISSUE THREAD

**Issue by frankool** [vietanhdev/anylabeling#73]
Point +, Point -, Rect....to add shortcuts to this functions can be helpful for fast labeling. Including add shape to label only pressing a number from example. Mapping the classes to numbers and pressing only the number the shape can be added to this class, every time that i create a shape i spend more time refining and selecting the class of the shape.
Thanks for the effort.

**Comment by vietanhdev** [comment]
This pull request added Q, E for points: https://github.com/vietanhdev/anylabeling/pull/98
