### ISSUE TITLE
Some issues with 0.1.1

### ISSUE THREAD

**Issue by omaiyiwa** [vietanhdev/anylabeling#8]
Thank you for solving the problem that the point cannot be removed in 0.9.0, but in version 0.1.1, when I use + point and then finish object, I need to re-enter the object category every time, 
![微信截图_20230413094510](https://user-images.githubusercontent.com/85824812/231627563-dbbb3fc6-f8fd-40ce-af67-b7e592c427b5.png)
but after I mark it twice with + rect (enter the object category, it doesn’t work once), switch +point and the object category will appear. 
![微信截图_20230413095512](https://user-images.githubusercontent.com/85824812/231627655-610be6ea-44f6-4f1c-9032-fc9046b93568.png)
But at this time the category name does not appear on the input box. Need to switch to other categories first,
![微信截图_20230413095544](https://user-images.githubusercontent.com/85824812/231627704-b5a2dba9-946b-41cc-95e2-484191e74924.png)
![微信截图_20230413095557](https://user-images.githubusercontent.com/85824812/231627706-c6573877-7254-4e1d-bb40-3093bdf73867.png)
I don't know if it is a bug, but I hope to have the same label setting, just like Labelimg. Will make repetitive work easier.

**Comment by omaiyiwa** [comment]
By the way, if I want to enable automatic saving by default, where do I need to modify the code

**Comment by vietanhdev** [comment]
@omaiyiwa Thank you very much for your bug report.
- Please check the fix in v0.1.6: https://github.com/vietanhdev/anylabeling/releases/tag/v0.1.6.
- Enable automatic saving: File > Save Automatically.
