### ISSUE TITLE
Importing annotations to anylabeling

### ISSUE THREAD

**Issue by thangngoc89** [vietanhdev/anylabeling#83]
Hello from a fellow Vietnamese @vietanhdev, 

Thank you for releasing this amazing product as open source. I currently have a lot of auto-generated masks that need to be checked and corrected if necessary. These masks are from SAM with a lot of post-processing.
The current format of these masks are binary masks.

I'm wondering if it's possible to import masks to anylabeling and edit?

TIA

**Comment by vietanhdev** [comment]
Hi @thangngoc89 !
AnyLabeling does not support mask labeling at the moment.

**Comment by hayleeXinyi** [comment]
You can output the intermediate results of sam as a json file, and when you have a json file with the same name and the same folder as the image, you can display the mask in anylabeling.
Good luck!

**Comment by thangngoc89** [comment]
@vietanhdev @hayleeXinyi hey. Thank you both for your answers. I've checked the format of the json file of Anylabeling and it seems quite simple. However, converting from binary mask to polygon is a lossy process so it's a blocker for me. 

Keep up the good work :)

**Comment by ryouchinsa** [comment]
Thanks for your great tool AnyLabeling.

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, you can drag & drop the COCO RLE JSON file of the SA-1B dataset to the labels table to import mask annotations.
You can drag & drop the mask images, too.

[Segment Anything 1 Billion (SA-1B)](https://ai.meta.com/datasets/segment-anything-downloads/) is a dataset designed for training general-purpose object segmentation models from open world images.

![dragDropRLEJSONFilesXML](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/c15b6458-9dfa-44f1-94e7-320e306a4554)

**Comment by ryouchinsa** [comment]
Improved "Create polygon using SAM" feature so that you can label pixels using the pixels option. You can label [Segment Anything 1 Billion (SA-1B)](https://ai.meta.com/datasets/segment-anything-downloads/) like dataset by yourself.

![sam-pixels](https://github.com/facebookresearch/segment-anything/assets/1954306/d828c18b-6fda-4258-b866-21bc34a0d17f)
