### ISSUE TITLE
when I load my own model, the program crashes

### ISSUE THREAD

**Issue by Miki-lin** [vietanhdev/anylabeling#85]
![image](https://github.com/vietanhdev/anylabeling/assets/54935281/0522bbb9-678c-44eb-9ddd-855a9fb5123d)

**Comment by Miki-lin** [comment]
I modify the onnx input and fix it.
![image](https://github.com/vietanhdev/anylabeling/assets/54935281/18c66bb8-1345-4113-a09e-6c4c1ff2214d)

**Comment by jueqiang** [comment]
I am encountering the same issue. Would you like to share more detailed descriptions of how to solve that issue? The image size I am using is 256*256. I have changed the 'input_size:' in .yaml file to '256' already. However, it does not solve my issue. /(ㄒoㄒ)/~~

**Comment by vietanhdev** [comment]
Please use v0.3.3 and [samexporter](https://github.com/vietanhdev/samexporter) for model exporting.
